#!/usr/bin/env python3
"""Write THIRD-PARTY-NOTICES from the dependency tree.

Every dependency is under a permissive license whose one condition is
that its copyright and license notice travel with binaries built from it
(SPEC 21.5). This collects each package's license files from the local
cargo registry and writes them, once per distinct text, with the packages
they apply to. Rerun after changing Cargo.lock:

    python3 scripts/third-party-notices.py > THIRD-PARTY-NOTICES
"""

import hashlib
import json
import os
import subprocess
import sys

LICENSE_FILE_PREFIXES = ("LICENSE", "LICENCE", "COPYING", "NOTICE")


def main() -> None:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    metadata = json.loads(
        subprocess.check_output(
            ["cargo", "metadata", "--format-version", "1", "--locked"], cwd=root
        )
    )
    workspace = set(metadata["workspace_members"])
    packages = sorted(
        (p for p in metadata["packages"] if p["id"] not in workspace),
        key=lambda p: (p["name"], p["version"]),
    )
    texts: dict[str, str] = {}
    users: dict[str, list[str]] = {}
    missing = []
    out = [
        "Third-party notices for Distributed-JBOD",
        "",
        "Distributed-JBOD is licensed under the GNU Affero General Public",
        "License, version 3 (see LICENSE). The binaries also contain the",
        "following packages, each under its own permissive license, listed",
        "here with the notices those licenses ask to be kept. Generated by",
        "scripts/third-party-notices.py from Cargo.lock.",
        "",
        "Packages",
        "--------",
    ]
    for p in packages:
        out.append(f"{p['name']} {p['version']}  ({p.get('license') or 'see license file'})"
                   + (f"  {p['repository']}" if p.get("repository") else ""))
        directory = os.path.dirname(p["manifest_path"])
        found = sorted(
            name for name in os.listdir(directory)
            if name.upper().startswith(LICENSE_FILE_PREFIXES) and os.path.isfile(os.path.join(directory, name))
        )
        if not found:
            missing.append(f"{p['name']} {p['version']}")
        for name in found:
            with open(os.path.join(directory, name), encoding="utf-8", errors="replace") as f:
                text = f.read().strip()
            key = hashlib.sha256(text.encode()).hexdigest()
            texts.setdefault(key, text)
            users.setdefault(key, []).append(f"{p['name']} {p['version']} ({name})")
    if missing:
        out += ["", "Packages whose source carries no license file (their license is",
                "named above and applies as stated in their Cargo.toml):"]
        out += [f"  {m}" for m in missing]
    out += ["", "Notices", "-------"]
    for key in sorted(texts, key=lambda k: users[k][0]):
        out += ["", "=" * 72, "Applies to:"]
        out += [f"  {u}" for u in users[key]]
        out += ["-" * 72, texts[key]]
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
